allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@remotion/bundler@4.0.500"
  - "@remotion/canvas-capture@4.0.500"
  - "@remotion/cli@4.0.500"
  - "@remotion/compositor-darwin-arm64@4.0.500"
  - "@remotion/compositor-darwin-x64@4.0.500"
  - "@remotion/compositor-linux-arm64-gnu@4.0.500"
  - "@remotion/compositor-linux-arm64-musl@4.0.500"
  - "@remotion/compositor-linux-x64-gnu@4.0.500"
  - "@remotion/compositor-linux-x64-musl@4.0.500"
  - "@remotion/compositor-win32-x64-msvc@4.0.500"
  - "@remotion/drag-and-drop@4.0.500"
  - "@remotion/licensing@4.0.500"
  - "@remotion/media-parser@4.0.500"
  - "@remotion/media-utils@4.0.500"
  - "@remotion/media@4.0.500"
  - "@remotion/player@4.0.500"
  - "@remotion/renderer@4.0.500"
  - "@remotion/streaming@4.0.500"
  - "@remotion/studio-server@4.0.500"
  - "@remotion/studio-shared@4.0.500"
  - "@remotion/studio@4.0.500"
  - "@remotion/timeline-utils@4.0.500"
  - "@remotion/web-renderer@4.0.500"
  - "@remotion/zod-types@4.0.500"
  - remotion@4.0.500
